services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - aw-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - aw-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - aw-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # Porta para conexões AMQP
      - "15672:15672" # Porta para o painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - aw-network

volumes:
  grafana-storage:
  prometheus-data:

networks:
  aw-network:
