global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-pix'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: "pix-app"
