server:
  port: 8081

spring:
  application:
    name: pix project
  data:
    mongodb:
      uri: mongodb://localhost:27017/transacoes
      auto-index-creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/pix
    username: root
    password: Santosfc@1912
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  metrics:
    export:
      prometheus:
        enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      rabbitmqCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 10
        maxWaitDurationInHalfOpenState: 5000
        automaticTransitionFromOpenToHalfOpenEnabled: true